package integration;

/**
 * Displays the total collected revenue to the console each time a new sale is completed.
 * This class implements the RevenueObserver interface and is part of the observer pattern.
 */
public class TotalRevenueView implements RevenueObserver {
    private double totalRevenue = 0;

    /**
     * Called when a new sale generates revenue. The total revenue is updated and
     * displayed in the console.
     *
     * @param amount The revenue generated by the recent sale.
     */
    @Override
    public void newRevenue(double amount) {
        totalRevenue += amount;
        System.out.println("Total revenue is now: " + String.format("%.2f", totalRevenue) + " SEK");
    }
}
