package integration;

import java.io.FileWriter;
import java.io.IOException;

/**
 * This class logs the total revenue to a file each time a sale is completed.
 * It implements the RevenueObserver interface and appends each revenue update
 * to a text file named "total-revenue.txt" as seen below
 */
public class TotalRevenueFileOutput implements RevenueObserver {
    private static final String FILE_NAME = "total-revenue.txt";
    private double totalRevenue = 0;

    /**
     * Called whenever a new revenue is generated from a completed sale.
     * Appends the new total revenue to the output file.
     *
     * @param amount The amount of revenue generated by the recent sale.
     */
    @Override
    public void newRevenue(double amount) {
        totalRevenue += amount;
        try (FileWriter writer = new FileWriter(FILE_NAME, true)) { // true = append mode
            writer.write("Total revenue is now: " + String.format("%.2f", totalRevenue) + " SEK\n");
        } catch (IOException e) {
            System.out.println("ERROR writing to file: " + e.getMessage());
        }
    }
}
